### ISSUE TITLE
Améliorer l'affichage des données sur la carte

### ISSUE THREAD

**Issue by mart-84** [hunkanome/AGILE-KroustyTour#41]
La carte est vraiment illisible, aussi bien en terme de couleurs, que de taille des points, etc.

On pourrait essayer de mettre des icones pour matérialiser les points importants (warehouse, delivery sélectionnée, ...)
Voir [GraphicsContext.drawPath](https://docs.oracle.com/javase/8/javafx/api/javafx/scene/canvas/GraphicsContext.html#drawImage-javafx.scene.image.Image-double-double-double-double- ) pour afficher une image sur le Canvas.

**Comment by ant0-sb** [comment]
Je te laisse checker et accepter. Pour l'instant il y a que les affichages de la Warehouse et du point sélectionné qui ont été modifiés. À voir ce qu'on veut faire pour l'affichage des tours plus tard.
